[alembic]
script_location = alembic

# Alembic переиспользует этот URL, если его не переопределить в env.py.
sqlalchemy.url = postgresql+asyncpg://postgres:postgres@db:5432/iot_monitor

[loggers]
keys = root,sqlalchemy,alembic
qualname = %(path)s
handlers = console
level = INFO

[handlers]
keys = console
handler = console
formatter = generic

[formatter]
keys = generic
format = %(levelname)-5.5s [%(name)s] %(message)s

[logger_root]
level = INFO
handlers = console

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

